//
//  ContactListWorker.swift
//  Whatsapp
//
//  Created by Asad Khan on 2/2/18.
//  Copyright (c) 2018 Asad Khan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ContactListWorker
{
    func retrieveContacts(@escaping completionHandler:)
  {
    
    ContactWorker().getAllContacts { (contacts) in
        
        
    }
  }
}
