//
//  ContactListInteractor.swift
//  Whatsapp
//
//  Created by Asad Khan on 2/2/18.
//  Copyright (c) 2018 Asad Khan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ContactListBusinessLogic
{
  func fetchContacts(request: ContactList.FetchContacts.Request)
}

protocol ContactListDataStore
{
  //var name: String { get set }
}

class ContactListInteractor: ContactListBusinessLogic, ContactListDataStore
{
  var presenter: ContactListPresentationLogic?
  var worker: ContactListWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func fetchContacts(request: ContactList.FetchContacts.Request)
  {
    worker = ContactListWorker()
    worker?.retrieveContacts()
    
    ordersWorker.fetchOrders { (orders) -> Void in
        self.orders = orders
        let response = ListOrders.FetchOrders.Response(orders: orders)
        self.presenter?.presentFetchedOrders(response: response)
    }
    
  
  }
}
