//
//  ContactListPresenter.swift
//  Whatsapp
//
//  Created by Asad Khan on 2/2/18.
//  Copyright (c) 2018 Asad Khan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ContactListPresentationLogic
{
  func presentSomething(response: ContactList.Something.Response)
}

class ContactListPresenter: ContactListPresentationLogic
{
  weak var viewController: ContactListDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: ContactList.Something.Response)
  {
    let viewModel = ContactList.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
